#!/bin/bash

####### HELP ########################################################
#
# Command completion (add to .bashrc):
#
#   complete -W 'project git-cui clear-panes kill' mux
#
# Usage outside tmux:
#
#   mux # starts tmux
#   mux project # create project in current directory
#                 # (two windows, the first is git-cui)
#
# Usage inside tmux:
#
#   mux git-cui # split current window to git console user interface
#   mux kill # kills tmux
#   mux clean-panes # kills all panes in window except active
#   mux close-window # close current window with all panes
#
#####################################################################

# set -e

function mux-git-cui() {
	tmux splitw
	tmux send-keys 'watch -n '''0,3''' git s' C-m
	tmux splitw
	tmux send-keys 'watch -n '''1''' git branch' C-m
	tmux select-layout main-vertical
	tmux select-pane -t 0
	mux-set-pane-width 1 30
}

function mux-clear-panes() {
	if [ "`tmux list-panes | wc -l`" != "1" ]; then
		tmux kill-pane -a -t `tmux list-panes | grep active | cut -d: -f1`
	fi
}

function mux-set-pane-width() {
	pane="$1"
	new_width="$2"

	pane_width=`tmux list-panes | grep $pane: | cut -dx -f1 | cut -d[ -f2`
	resize_to=$((pane_width - new_width))

	tmux resize-pane -R $resize_to
}

COMMAND="$1"
case $COMMAND in
	"")
		tmux
		;;

	project)
		SESSION_NAME=Git_CUI

		tmux start-server
		tmux set-option -g base-index 1
		tmux new-session -d -s $SESSION_NAME -n 'git cui'
		tmux set-option default-path .

		# (1nd) window "git cui"
		mux-git-cui

		# (2nd) window home
		tmux new-window -n 'home'
		tmux send-keys -t $SESSION_NAME:2 'cd ~' C-m

		tmux select-window -t $SESSION_NAME:1
		tmux -u attach-session
		;;

	git-cui)
		tmux set-window-option default-path `pwd`
		mux-clear-panes
		mux-git-cui
		;;

	clear-panes)
		mux-clear-panes
		;;

	close-window)
		tmux kill-window
		;;

	kill)
		tmux kill-session
		;;

	*)
		echo mux: Command *$COMMAND* is unknown.
		;;

esac
