#!/bin/bash -e

####### HELP ########################################################
#
# Command completion (add to .bashrc):
#
#   complete -W 'project git-cui clear-panes kill close' muxig
#
# Usage outside tmux:
#
#   muxig # starts tmux
#   muxig project # create project in current directory
#                 # (two windows, the first is git-cui)
#
# Usage inside tmux:
#
#   muxig git-cui # split current window to git console user interface
#   muxig kill # kills tmux
#   muxig clear-panes # kills all panes in window except active
#   muxig close-window # close current window with all panes
#
#####################################################################

function muxig-git-cui() {
	tmux splitw
	tmux send-keys 'watch --no-title --color -n '''0,3''' git status --short -b' C-m
	tmux splitw
	tmux send-keys 'watch --no-title --color -n '''1''' git branch' C-m
	tmux select-layout main-vertical > /dev/null
	tmux select-pane -t 0
	muxig-set-pane-width 1 30
}

function muxig-clear-panes() {
	if [ "`tmux list-panes | wc -l`" != "1" ]; then
		tmux kill-pane -a -t `tmux list-panes | grep active | cut -d: -f1`
	fi
}

function muxig-set-pane-width() {
	pane="$1"
	new_width="$2"

	pane_width=`tmux list-panes | grep $pane: | cut -dx -f1 | cut -d[ -f2`
	resize_to=$((pane_width - new_width))

	if [ $resize_to -gt 0 ]; then
		tmux resize-pane -t $pane -R $resize_to ;
	else
		tmux resize-pane -t $pane -L $((- resize_to)) ;
	fi
}

COMMAND="$1"
case $COMMAND in
	"")
		tmux
		;;

	project)
		SESSION_NAME=Git_CUI

		tmux start-server
		tmux set-option -g base-index 1
		tmux new-session -d -s $SESSION_NAME -n 'git cui'

		# (1nd) window "git cui"
		muxig-git-cui

		# (2nd) window home
		tmux new-window -n 'home'
		tmux send-keys -t $SESSION_NAME:2 'cd ~' C-m

		tmux select-window -t $SESSION_NAME:1
		tmux -u attach-session
		;;

	git-cui)
		tmux set-window-option default-path `pwd` > /dev/null
		muxig-clear-panes
		muxig-git-cui
		;;

	clear-panes)
		muxig-clear-panes
		;;

	close-window)
		tmux kill-window
		;;

	kill)
		tmux kill-session
		;;

	*)
		echo muxig: Command *$COMMAND* is unknown.
		;;

esac
